---
config:
    general:
        threads: 1
        verbose: true
        storedirectory: /home/armijn/debian
    repositories:
        debian:
            mirror: http://ftp.nluug.nl/pub/os/Linux/distr/debian/
            # categories: [dsc, source, patch, binary, dev]
            categories: [binary]
            # directories: [main, non-free, contrib]
            directories: [main]
            # architectures: [all, i386, amd64, arm64, armhf]
            architectures: [amd64]
            enabled: false
        ubuntu:
            mirror: http://ftp.nluug.nl/pub/os/Linux/distr/ubuntu/
            categories: [binary]
            directories: [main, universe, multiverse]
            architectures: [amd64]
