---
general:
    # directory for unpacking. By default this is /tmp or
    # whatever the default set by the system is.
    # tempdir: /tmp
    verbose: true
yara:
    # directory where pre-compiled yara rules can be found
    compiled_rules: /home/armijn/yara/binary
meilisearch:
    # The host for the Meilisearch server.
    host: 127.0.0.1

    # The port for the Meilisearch server.
    port: 7700

    # the index to search
    #index: ctags
    index: strings
vulnerablecode:
    # endpoint url
    url: https://localhost/api

    # user name
    # user: vulnerablecode

    # password
    # password: password
proximity:
    # minimal length of strings, recommended to not go below 5
    # string_min_cutoff: 8

    # maximal length of strings, recommended to not go above 200
    # string_max_cutoff: 200

    # minimal length of functions/variable names, recommended
    # to not go below 2
    # identifier_cutoff: 2

    # ignore weak ELF symbols. Recommended to set to 'true'
    ignore_weak_symbols: true
